# Generated by Django 3.1.3 on 2020-12-08 13:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20201208_0839'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('events', django.db.models.manager.Manager()),
            ],
        ),
    ]
